name: shelf_firebase_auth
description: Shelf middleware for authenticating Firebase users.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: any
  shelf: any
  pointycastle: any
  asn1lib: any 

dev_dependencies:
  pedantic: any
  test: any